### ISSUE TITLE
Intellisense not working with Scholarly XML

### ISSUE THREAD

**Issue by JayDaley** [raffazizzi/vscode-sxml#20]
Intellisense (code suggestion and completion) doesn't work with Scholarly XML.  ctrl-space brings up "Loading ..." and sticks there.  Intellisense works fine with other languages/plugins.  Any help much appreciated.

**Comment by Cicorione** [comment]
Hi, I am testing this extension out and I am having the same issue.
I can't get any suggestions while typing and `ctrl-space` brings up `loading...` but nothing happens:

```
Scholarly XML v0.3.0

Version: 1.81.1
Release: 23222
Commit: aef377c42cea6e9aea642829953104f07097abfa
Date: 2023-08-10T18:29:01.714Z
Electron: 22.3.18
ElectronBuildId: undefined
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.1.0-17-amd64
```

Any recommendation to fix it?

Thanks! 🙏

**Comment by raffazizzi** [comment]
Hello @Cicorione. Currently, Scholarly XML only supports RelaxNG schemas associated via an `<?xml-model?>` processing instruction. This needs to be expressed as indicated in the README file. I see from the linked issue on speedata that you're trying to get their schema to work, here is what you want to do:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model 
  href="https://raw.githubusercontent.com/speedata/publisher/develop/schema/layoutschema-de.rng" 
  type="application/xml"
  schematypens="http://relaxng.org/ns/structure/1.0"?>

<Layout xmlns="urn:speedata.de:2009/publisher/en"
	xmlns:sd="urn:speedata:2009/publisher/functions/en">
  [...]
</Layout>
```

As you can see, this makes it possible to access the Intellisense features: 

![image](https://github.com/raffazizzi/vscode-sxml/assets/144770/94a49fa8-bb95-4380-8327-b7d28f991aca)


Admittedly, the extension should provide better feedback to users when the association via `<?xml-model?>` isn't done correctly. So I opened a separate issue to deal with that: https://github.com/raffazizzi/vscode-sxml/issues/36

Thanks for reporting!

**Comment by Cicorione** [comment]
Nice!

Thanks to help me how with this!!! 🙏

**Comment by Cicorione** [comment]
If I don't bother you I would have another question for you... 🙏

How can I change this to load a local definition:

`href="https://raw.githubusercontent.com/speedata/publisher/develop/schema/layoutschema-en.rng"`

Is it actually possible, I can't see any reference here: https://www.w3.org/TR/xml-model/

**Comment by raffazizzi** [comment]
Sure, here are some options:

## Relative path

Use this to point to a location relative to your XML file. If your XML and the schema are in the same folder, you can just do this:

```href="layoutschema-de.rng"```

Or if it's one level up and inside a folder named "schema", you can do this:

```href="../schema/layoutschema-de.rng"```

## Absolute path

You can specify the absolute path on your machine without using the `file://` protocol, just enter `/FULL/PATH/TO/`. For example if your file is located in `/usr/share/speedata-publisher/schema`:

```href="/usr/share/speedata-publisher/schema/layoutschema-en.rng"```

On Windows, you may need to specify the drive, e.g.:

```C:\PATH\TO\layoutschema-en.rng```

**Comment by Cicorione** [comment]
Hi, thank you very much again!

I have not idea how much this information is going to be relevant for you, but when I try to load a local `schema` it tells me that **RNG schema is incorrect:**

![image](https://github.com/raffazizzi/vscode-sxml/assets/19494201/0d60571b-be29-4a27-9b9b-1f65d3dd83c2)

🤷‍♂️

**Comment by raffazizzi** [comment]
@Cicorione the status message is once again not very helpful, but I wonder if it is also accompanied by a pop-up that says "Could not parse schema" on the bottom right? (Though I notice that you have notifications turned off)

![image](https://github.com/raffazizzi/vscode-sxml/assets/144770/ce9a04cd-eb45-4a54-ab6e-63696a87f323)

What I think is happening is that there is, in fact, no `layoutschema-en.rng` file at `/usr/share/speedata-publisher/schema/layoutschema-en.rng`. Are you sure it's in that location and it has the right filename? Have you tried a relative path — e.g. placing both the XML and the schema in the same folder and changing the href to `href="layoutschema-de.rng"`?

**Comment by Cicorione** [comment]
@raffazizzi I am very sorry, I forgot I made some changes at the local RNG file making it invalid, restoring the original file fixed the issue, my bad... 😭
